### ISSUE TITLE
Setting functional curve coefficient at pyswmm

### ISSUE THREAD

**Issue by joaolponciano** [pyswmm/pyswmm#167]
First I would like to thank you for pyswmm @bemcdonnell,

I was wondering if it's possible to set the coefficient of the functional curve or any other parameter related to the capacity of the storage units.

Thanks.

**Comment by dickinsonre** [comment]
ditto on the thanks for pyswmm @bemcdonnell,

**Comment by bemcdonnell** [comment]
@joaolponciano, I think this would be a nice feature.  PySWMM supports basic node interfacing but nothing specific to storage properties.  I think you could expose a nice API for the storage nodes that would let you get/set those properties:

in OWA-SWMM: https://github.com/OpenWaterAnalytics/Stormwater-Management-Model/blob/develop/src/node.c#L648-L734

Here is what the parser does.  
```C
int storage_readParams(SWMM_Project *sp, int j, int k, char* tok[], int ntoks)
//
//  Input:   j = node index
//           k = storage unit index
//           tok[] = array of string tokens
//           ntoks = number of tokens
//  Output:  returns an error message
//  Purpose: reads a storage unit's properties from a tokenized line of input.
//
//  Format of input line is:
//     nodeID  elev  maxDepth  initDepth  FUNCTIONAL a1 a2 a0 aPond fEvap (infil)
//     nodeID  elev  maxDepth  initDepth  TABULAR    curveID  aPond fEvap (infil)
//
{
    int    i, m, n;
    double x[9];
    char*  id;

    // --- get ID name
    if ( ntoks < 6 ) return error_setInpError(sp, ERR_ITEMS, "");
    id = project_findID(sp, NODE, tok[0]);
    if ( id == NULL ) return error_setInpError(sp, ERR_NAME, tok[0]);

    // --- get invert elev, max. depth, & init. depth
    for ( i = 1; i <= 3; i++ )
    {
        if ( ! getDouble(tok[i], &x[i-1]) )
            return error_setInpError(sp, ERR_NUMBER, tok[i]);
    }

    // --- get surf. area relation type
    m = findmatch(tok[4], RelationWords);
    if ( m < 0 ) return error_setInpError(sp, ERR_KEYWORD, tok[4]);
    x[3] = 0.0;                        // a1 
    x[4] = 0.0;                        // a2
    x[5] = 0.0;                        // a0
    x[6] = -1.0;                       // curveID
    x[7] = 0.0;                        // aPond
    x[8] = 0.0;                        // fEvap

    // --- get surf. area function coeffs.
    if ( m == FUNCTIONAL )
    {
        for (i=5; i<=7; i++)
        {
            if ( i < ntoks )
            {
                if ( ! getDouble(tok[i], &x[i-2]) )
                    return error_setInpError(sp, ERR_NUMBER, tok[i]);
            }
        }
        n = 8;
    }

    // --- get surf. area curve name
    else
    {
        m = project_findObject(sp, CURVE, tok[5]);
        if ( m < 0 ) return error_setInpError(sp, ERR_NAME, tok[5]);
        x[6] = m;
        n = 6;
    }

    // --- ignore next token if present (deprecated ponded area property)      //(5.1.007) 
    if ( ntoks > n)
    {
        if ( ! getDouble(tok[n], &x[7]) )
            return error_setInpError(sp, ERR_NUMBER, tok[n]);
        n++;
    }

    // --- get evaporation fraction if present
    if ( ntoks > n )
    {
        if ( ! getDouble(tok[n], &x[8]) )
            return error_setInpError(sp, ERR_NUMBER, tok[n]);
        n++;
    }

    // --- add parameters to storage unit object
    sp->Node[j].ID = id;
    node_setParams(sp, j, STORAGE, k, x);

    // --- read exfiltration parameters if present
    if ( ntoks > n ) return exfil_readStorageParams(sp, k, tok, ntoks, n);         //(5.1.007)
    return 0;
}

```

You could write some simple interfacing functions and then expose them in TOOLKITAPI.C

https://github.com/OpenWaterAnalytics/Stormwater-Management-Model/blob/develop/src/toolkitAPI.c

Then they could be wrapped with PySWMM.  Does that sound like something you would be interested in  working on? We would be happy to provide guidance along the way.

**Comment by joaolponciano** [comment]
@bemcdonnell, yeah, it's sounds like something I would be interested in working on, with your guidance I think I can do it.

 I should just add a parameter at the nodes code (like it's in the https://github.com/OpenWaterAnalytics/Stormwater-Management-Model/blob/develop/src/node.c#L112-L186)  or should I do a new routine for the storage units?

Do you think this will take too much time? Actually, I intend to use this in a work which the deadline is not so far.

Thanks for the support.

**Comment by bemcdonnell** [comment]
@joaolponciano - let's talk about this over here: https://github.com/OpenWaterAnalytics/Stormwater-Management-Model/issues/189

**Comment by bemcdonnell** [comment]
Completed in pyswmm-v2
