### ISSUE TITLE
Conduit length and max depth

### ISSUE THREAD

**Issue by tuuliina** [pyswmm/pyswmm#174]
Thank you for your efforts in making pyswmm!

I would like to be able to get and set conduit length and max depth (diameter) with pyswmm. Are you planning to create Link attributes for them?

**Comment by bemcdonnell** [comment]
@tuuliina, yes we are going to expose all of these options.  We need a lot of help - would you be interested in making this contributions?

**Comment by dickinsonre** [comment]
this is one of my favorite parts of SWMM,  you might want to consider changing the loss coefficients, shape, width and roughness as well  Inverts?  Ie Slope as well which can be a quasi design tool

**Comment by bemcdonnell** [comment]
@Husnain2244, as of this moment, the `Conduit` information has not been exposed in the OWASWMM-API.  My suggestion is that your work around is 

1. Open INP file with python `swmmio`
2. Edit the Conduit Length
3. Save the INP file
4. Open With PySWMM
5. Run `simulation`
6.  ... your analysis. 

We are currently roadmapping some of the future features of pyswmm and this is one thing we have in mind!  Some values (such as length) required a validation and checks before a value get inserted in the data model.  Therefore, it is less straightforward to expose the parameters.  Thanks for using pyswmm!

**Comment by bemcdonnell** [comment]
Completed in pyswmm-v2
