### ISSUE TITLE
 subcatchment percent_impervious couldn't be reset.

### ISSUE THREAD

**Issue by xiang3874264** [pyswmm/pyswmm#235]
**Describe the bug**
When you want to reset the subcatchment's precent_impervious,  the `s1.percent_impervious = xx` does not work. However, the resets of other parameters like area and slope may work well.

**To Reproduce**
`sim=Simulation("D:\\Downloads\\pyswmm-master\\pyswmm-master\\docs\\source\\examples\\swmm_example.inp")`
`s1 = Subcatchments(sim)["S1"]`

[In]: s1.percent_impervious
[Out]: 0.75
[In]: s1.percent_impervious = 0.65
[In]: s1.percent_impervious
[Out]: 0.75
    
**Screenshots**
![图片](https://user-images.githubusercontent.com/65355776/81955505-c1b09200-963c-11ea-8e1c-de2eff212b41.png)

**Desktop:**
 - Windows
 - Python 3.7-x64
 - PySWMM v0.6.1

**Comment by jennwuu** [comment]
thanks for reporting this. 

i don't think setter function exists in the OWA/swmm yet. i think pyswmm setter function for percent_impervious should be commented out until the setter is available in OWA/swmm. @bemcdonnell

**Comment by bemcdonnell** [comment]
https://github.com/OpenWaterAnalytics/Stormwater-Management-Model/blob/4ce7352511157bd4b635ee80a005e47ff21cd23d/src/toolkitAPI.c#L739-L788

To confirm @jennwuu, yes. There is a validation step required to make this work. Sorry that I opened up that function before finishing it! @xiang3874264, Do you have the ability to dive into SWMM and update this API call?

**Comment by xiang3874264** [comment]
I see, thank you. Sorry that updating the API call exceeds my ability @jennwuu.

**Comment by noneaddress** [comment]
Hope this bug can be solved, thanks to the contribution of developers./(ㄒoㄒ)/~~

**Comment by bemcdonnell** [comment]
@noneaddress, just to clarify, this isn't actually a bug. It is just a feature we never implemented. ;-). I have a simple idea that might help that I am working on in the coming month.

**Comment by bemcdonnell** [comment]
Completed in pyswmm-v2
