### ISSUE TITLE
Missing tutorial file testmodel.inp

### ISSUE THREAD

**Issue by stoiver** [pyswmm/pyswmm#253]
Just checking out the online documentation for [pyswmm](https://pyswmm.readthedocs.io/en/stable/tutorial/tutorial.html)  which uses the file `testmodel.inp`. I can't find this file. It would be great if the file could be added to this repository.

**Comment by katmratliff** [comment]
@bemcdonnell do you have this file, or is this something we need to generate and post to the documentation?

@stoiver in the meantime, please check out the [Examples](https://pyswmm.readthedocs.io/en/stable/examples/examples.html) part of the documentation - that section does have a downloadable input file and some python code examples!

**Comment by bemcdonnell** [comment]
I do not have this file. I wonder if I just arbitrarily plopped that file name in for the documentation

**Comment by katmratliff** [comment]
@bemcdonnell ok thanks. When I get a chance, I'll make an actual `testmodel.inp` file that can be downloaded from the tutorial page and works with all the snippets of python code in the tutorial - or let me know if you have any other ideas!

**Comment by stoiver** [comment]
@katmratliff thanks for the pointer to the examples part of the documentation.
