### ISSUE TITLE
Subcatchment percent impervious can't be set

### ISSUE THREAD

**Issue by Zeeck972** [pyswmm/pyswmm#277]
The documentation mentions that  the subcatchment percent impervious can be set to another value, but in the latest version it is not valid.

![subcatchment](https://user-images.githubusercontent.com/82164554/114193027-b5ce6c80-9980-11eb-9ea6-bfa055d75afe.png)

It is also invalid in version 0.6.2,but the function is work in v0.5.0.I'm not sure in which recent version this bug occurred.

I also want to ask that if it is possible to change the Infiltration Model in pyswmm? I hope use Curve Number to simulation, but I did not find in the documentation how to change the model and set CN value in a subcatchment. If I needn't to change the model and CN value in multiple simulations, can I set them up in EPA-SWMM and run it in pyswmm? Will the reports be the same in EPA-SWMM and pyswmm?

**Comment by jennwuu** [comment]
This is an known bug in previous versions of pyswmm. It is documented here: https://github.com/OpenWaterAnalytics/pyswmm/issues/246

**Comment by Zeeck972** [comment]
Thank you for your reply. Maybe I can use the history version first.Could you tell me about Infiltration Model and CN value setting?

**Comment by jennwuu** [comment]
@Zeeck972 I don't think impervious fraction works in previous versions of pyswmm. Although pyswmm setters were set up, I don't think the variables were updating in the swmm model. Please test if you do go through with previous version of pyswmm. 

You can check out docs for subcatchment object here: https://pyswmm.readthedocs.io/en/latest/reference/subcatchments.html#pyswmm.subcatchments.Subcatchments

To my knowledge, these parameters do not exist yet in pyswmm.

**Comment by bemcdonnell** [comment]
Addressed through PR #512 for PySWMM-v2.x

**Comment by icosearcher** [comment]
Percent impervious can't be set.

ENV:
Name: pyswmm
Version: 2.1.0
Summary: Python Wrapper for SWMM5 API
Home-page: https://www.pyswmm.org
Author: Bryant E. McDonnell (See AUTHOR)


code:
with Simulation(inpff) as sim:
  s1 = Subcatchments(sim)["4"]
  print("s1.percent_impervious",s1.percent_impervious)
  s1.percent_impervious = float(0.15)
  print("s1.percent_impervious",s1.percent_impervious)


print:
s1.percent_impervious 0.3
s1.percent_impervious 0.3
