### ISSUE TITLE
Can the source of raingage be changed by pyswmm 

### ISSUE THREAD

**Issue by tianmaxingkong12** [pyswmm/pyswmm#287]
**Describe the bug**
I have many timeseries. I want to choose one timeserie by pyswmm in my application. Can the source of raingage be changed by pyswmm?

**Screenshots**
![image](https://user-images.githubusercontent.com/29156524/127600043-e2da6672-b9c8-4502-844d-d6af29352e7b.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Python Version Python 3.6-x86
 - PySWMM Version 1.0.1

**Comment by floriandorre** [comment]
Hi,

It would also be great to be able to load a Raingage file using pyswmm to avoid an error if the path is not fount

**Comment by jennwuu** [comment]
Hello! This feature is not available yet. However, you can adjust the rainfall within the simulation.

https://pyswmm.readthedocs.io/en/latest/reference/raingages.html

**Comment by swmm-js** [comment]
I've got a partially-tested solution for this in swmm-toolkit and Pyswmm. I would like to be assigned to this issue, if that's possible.

**Comment by bemcdonnell** [comment]
@swmm-js so you're proposing enlist some new API function to modify which existing timeseries a RG points to, correct?  If so, i believe this function would be first implemented into the OWA-SWMM repo in the toolkit.c/.h. then type maps established into swmm-python(swmm-toolkit), then finally, exposed to pyswmm.  Are you familiar with the workflow?  I will be happy to assign this to you.

**Comment by swmm-js** [comment]
Yes, I totally agree. Since this started as an issue here, I wanted to get your go-head before I submitted an issue on swmm-python and then asked for assignment there.

I have mods to

raingages.py
swmm5.py
toolkitapi.py
test_rainfallAPI.py
__init__.py

and followed the structure pattern of  swmm-toolkit with 10 files modified there. That's a ton of mods so I didn't want this to come out of the blue for them.

**Comment by swmm-js** [comment]
Real-world applications for changing raingage mid-sim or pre-sim would be:

- calibration when dominant raingage is indeterminate.
- virtual raingage co-modeling.
- future raingage datastreams are detected to be in error or missing.
- storm hybrid modeling.

These applications would add a good amount of value to Pyswmm.

**Comment by karosc** [comment]
@swmm-js , are you still interested in taking this on? I don't see forks of pyswmm or swmm-python in your account. Just want to touch base.

**Comment by swmm-js** [comment]
I must have mistakenly thought this idea was canned. 

I'm finishing the rainfall editing interface of swmmReact specifically to provide chartable results for these PySWMM changes. Without instant charting and demonstration I feel my contribution may be difficult to accept, the applications sound unrealistic when I just talk about them.

Today was the last day for nodes and links edit testing, so the rainfall tables are next. I've already got a demo with editable rainfall tables up, so it shouldn't take long. 

The pyswmm edits are on my laptop, which I haven't opened in a month. I maintain many github accounts. I'll start pushing these changes as soon as I can verify them in a more user-friendly way. I'm also terrible at Python.

**Comment by bemcdonnell** [comment]
Addressed through PR #512 for PySWMM-v2.x
