### ISSUE TITLE
Add parameters in subcatch

### ISSUE THREAD

**Issue by KrushilM** [pyswmm/pyswmm#308]
How to add more parameters such as saturated hydraulic conductivity or initial moisture deficiet to subcatch.param class, so it can be called while running simulation ?

Thanks in advance.

**Comment by bemcdonnell** [comment]
@KrushilM from SWMM, can you clarify the numbers you're interested in? I think you're asking for GW/Aquifer values:

https://github.com/OpenWaterAnalytics/Stormwater-Management-Model/blob/76b8ae7e39f07a659b51284effafe668394d7f29/src/solver/objects.h#L223-L284

**Comment by KrushilM** [comment]
Thank you for your prompt reply. I am interested in adding above mentioned parameters as callable quantities for sub-catchment the Green-Ampt method.

**Comment by bemcdonnell** [comment]
Addressed through PR #512 for PySWMM-v2.x
