### ISSUE TITLE
Possibility to set report_step using the Simulation class

### ISSUE THREAD

**Issue by floriandorre** [pyswmm/pyswmm#314]
Hi, 

Would it be possible to add the possibility to set the report_step value using the Simulation class ?

In my case I use step_advance but if the step_advance value is not the same as the initial report_step from the INP then I will not have the values expected in the OUT file.

For now the only way to do it is to update the INP file before loading it right ?

Thanks in advance for your help

**Comment by abhiramm7** [comment]
Hi @floriandorre, Sorry for the delay - it was just seven months 😅. Yes, right now, you would have to do it via input file. As far as I know, we would have to update the SWMM source code to expose the `report step` as a variable. Let us know if you are interested in working on it. We can guide you through it, and I promise it will not take seven months to get back to you :).

**Comment by floriandorre** [comment]
Hi @abhiramm7 thanks for the reply and no problem for the delay it was not an emergency at all :). I will pass the information to my colleagues since i'm no longer working on SWMM projects. (@georges-schutz)

**Comment by bemcdonnell** [comment]
Addressed through PR #512 for PySWMM-v2.x
