### ISSUE TITLE
May I ask why this link disappeared：http://pyswmm.readthedocs.io/en/latest/

### ISSUE THREAD

**Issue by YaoHainan** [pyswmm/pyswmm#432]
May I ask why this link disappeared：http://pyswmm.readthedocs.io/en/latest/

**Comment by YaoHainan** [comment]
The documentation on the official website is difficult to understand。

**Comment by bemcdonnell** [comment]
@YaoHainan could you help provide some information on where the docs are unclear?  We would love to improve them and make them more user friendly. Examples would be helpful. I will keep this as an issue so we can be sure to address it in pyswmm-v2 release.

**Comment by YaoHainan** [comment]
Thank you for your reply. I am getting used to the current document style.If I have any questions or suggestions, I will let you know as soon as possible.

**Comment by bemcdonnell** [comment]
@YaoHainan Thanks!!!
