### ISSUE TITLE
Setting a orifice setting using Simulation.initial_conditions callback

### ISSUE THREAD

**Issue by karosc** [pyswmm/pyswmm#435]
I was trying set a gate target_setting using the [Simulation.initial_conditions callback](https://github.com/pyswmm/pyswmm/blob/22aed805ec435dce93d0ccc084041e380827e01d/pyswmm/simulation.py#L170) and found it wasn't working.

It seems that swmm initializes all links with a target setting of 1 in [`link_initState`](https://github.com/pyswmm/Stormwater-Management-Model/blob/8266e4434bc9c23218bbf18fe57b0f3523d414ee/src/solver/link.c#LL522C33-L522C33). This `link_initState` function is called in [`project_init()`](https://github.com/pyswmm/Stormwater-Management-Model/blob/8266e4434bc9c23218bbf18fe57b0f3523d414ee/src/solver/project.c#L326), which is called in [`swmm_start`](https://github.com/pyswmm/Stormwater-Management-Model/blob/8266e4434bc9c23218bbf18fe57b0f3523d414ee/src/solver/swmm5.c#L410). So when `swmm_start` is called, all links get a target setting of 1.

In pyswmm, the `initial_conditions` callback is [called right before swmm_start](https://github.com/pyswmm/pyswmm/blob/22aed805ec435dce93d0ccc084041e380827e01d/pyswmm/simulation.py#L110), so any changes I make to link target_settings in the `initial_conditions` callback  are overwritten by 1 when `swmm_start` is called.

Is the order of operations here intentional? Or is this a bug?

**Comment by bemcdonnell** [comment]
Definitely a bugggggg

**Comment by karosc** [comment]
resolved by #446 with the addition of the new `Simulation.after_start()` callback
