### ISSUE TITLE
Setting the discharge coefficient of an orifice with pysmm

### ISSUE THREAD

**Issue by cheocl** [pyswmm/pyswmm#439]
I have attempted to create a loop using pyswmm to adjust the discharge coeff. for an orifice (r1) in swmm for every different fixed target_setting.
The r1 references link_object["R1"] what it is named in swmm and successfully updates the target_setting, however does not seem to implement the adjusted discharge coefficient.
The premise behind this is we have a physical system and have calibrated the discharge coefficient for each fixed orifice opening and would like to conduct extensive virtual testing to obtain more results.
What is the parameter name to adjust this discharge coeff. in pyswmm called, I cannot seem to find it within the r1 link object, am I looking in the right place?

I am not particularly adept in coding so I may simply be making a stupid error so any help would be appreciated.

**Comment by karosc** [comment]
pyswmm does not currently support adjusting the orifice discharge coefficient, which is held by the [cDisch](https://github.com/pyswmm/Stormwater-Management-Model/blob/8266e4434bc9c23218bbf18fe57b0f3523d414ee/src/solver/link.c#L364) prop of the orifice struct in the swmm code. You have to be careful when setting the cDisch param mid simulaton be cause SWMM uses it every timestep for [computing the gate settings](https://github.com/pyswmm/Stormwater-Management-Model/blob/8266e4434bc9c23218bbf18fe57b0f3523d414ee/src/solver/link.c#L1716-L1749) and more. If we wanted to add support, we could add a switch case to the toolkit.c file of swmm. We'd probably want to add a new swmm_setOrificeParamfunction, similar to the [swmm_setLinkParam](https://github.com/pyswmm/Stormwater-Management-Model/blob/8266e4434bc9c23218bbf18fe57b0f3523d414ee/src/solver/toolkit.c#LL752C49-L752C65). If you open an issue in the SWMM repo, we can put it on the to do list and pyswmm 2.0. Or you can take a stab at implementing it yourself and we can assist with reviewing and releasing a minor release.

**Comment by cheocl** [comment]
Thanks for the response, I will not be adjusting the cDish parameter mid simulation, rather updating the value inbetween simulations where simulation 1 has target_setting (x) and cDisch (a), simulation 2 has target_setting (y) and cDisch (b), etc.

I will work on implementing myself and check in later if I have any further issues

**Comment by cheocl** [comment]
Hi, I have added in the code listed here but I am having trouble compiling the code as it seems the version.h file cannot be found. The INCLUDE "version.h" throws an error with file not found. I searched through all directories and the header file is not there.

Have tried to complie the code both on Windows and Mac

Any help will be appreciated.

EXPORT_TOOLKIT int swmm_setOrificeParam(int index, double cDisch)
///
/// Input:   index = Index of desired ID
///          cDisch = Discharge coefficient value
/// Return:  API Error
/// Purpose: Sets Orifice Discharge Coefficient Parameter
{
    int error_code = 0;
    // Check if Open
    if(swmm_IsOpenFlag() == FALSE)
    {
        error_code = ERR_TKAPI_INPUTNOTOPEN;
    }
    // Check if object index is within bounds
    else if (index < 0 || index >= Nobjects[LINK])
    {
        error_code = ERR_TKAPI_OBJECT_INDEX;
    }
    else if (Link[index].type != ORIFICE)
    {
        error_code = ERR_TKAPI_OBJECT_TYPE;
    }
    else
    {
        int k = Link[index].subIndex;
        Orifice[k].cDisch = cDisch;
    }

    return error_code;
}

**Comment by karosc** [comment]
are you using cmake to compile? Version.h is created by cmake using the version.h.in file.

**Comment by bemcdonnell** [comment]
Addressed through PR #512 for PySWMM-v2.x
