### ISSUE TITLE
Can you edit the parameters and save the inp file?

### ISSUE THREAD

**Issue by mishranurag** [pyswmm/pyswmm#451]
I have a large model and I want to be able to edit parameters for specific subcatchments. Is it possible to edit the values of the parameters and then save the inp file?

Sincerely
~A

**Comment by karosc** [comment]
Until swmmio v1.0 is released, I'd check [swmm-api](https://pypi.org/project/swmm-api/). Future work will tie swmmio and pyswmm together in a meaningful way with full coverage of input file sections. Right now it has partial coverage with known bugs, swmm-api might be more stable.

**Comment by mishranurag** [comment]
Thank You
