### ISSUE TITLE
Pyswmm explotes during a simulating iterative process

### ISSUE THREAD

**Issue by EnricBonet** [pyswmm/pyswmm#456]
The issue is that I'm using pyswmm in python for simulating in a iterative process, pyswmm explotes when the iterative process arrives to the 125 iteration (always, although I change the boundary conditions or anything), so the rpt file descrives the problem:   ERROR 331: cannot open hotstart interface file HotStart.hsf.
Although it is quite strange because it always uses the same HotStart.hsf file during all simulations (in case I create a new HotStar.hsf in every simulation the result is the same), and in case you simulate in SWMM with the las iteration files: the .inp, .dat etc, SWMM works properly so it has not sense. 

On the other hand,the code begins with a new object  in every simulation ( with Simulation('C:\\GuadalhorceSimulation_gui_V2.inp','rpt.rpt','out.out') as sim:)

PC
 - OS: Windows
 - Python Version [Python 3.8.16]
 - PySWMM Version [1.3.0]

**Comment by bemcdonnell** [comment]
@EnricBonet it would really be helpful for us if you shared a condensed version of how you have implemented pyswmm in your code.
