### ISSUE TITLE
I encountered "Run Completefree(): double free detected in tcache 2" when running pyswmm in docker.

### ISSUE THREAD

**Issue by t298** [pyswmm/pyswmm#457]
I didn't run into this problem running python files on win11, but he did when I built the code online.
My code is as follows:
![image](https://github.com/pyswmm/pyswmm/assets/49806840/6834a3c9-bff1-4979-b6dc-1f40698133e0)
My environment is as follows:
![image](https://github.com/pyswmm/pyswmm/assets/49806840/aca50476-4232-4dd1-9bee-f63d2b495d0e)

**Comment by bemcdonnell** [comment]
@t298 can you add a screenshot of the error?

**Comment by t298** [comment]
![image](https://github.com/pyswmm/pyswmm/assets/49806840/9d3ba61d-f6d8-4222-ad8e-6e044474c5b3)
@bemcdonnell

**Comment by bemcdonnell** [comment]
@t298 any chance you could zip and share your model files? I’d like to recreate this to see what is going on.

**Comment by t298** [comment]
[file.zip](https://github.com/pyswmm/pyswmm/files/11933614/file.zip)
@bemcdonnell

**Comment by t298** [comment]
I am very sorry that this bug was caused by my problem, which has been solved now.
![image](https://github.com/pyswmm/pyswmm/assets/49806840/d80456ed-8459-44a9-956c-4e70255e7771)
