### ISSUE TITLE
Cannot install pyswmm on MacOs

### ISSUE THREAD

**Issue by aginpatrick** [pyswmm/pyswmm#462]
On my MacBook Pro (Apple M1 - MacOS 12.5.1 Monterey), I try to install pyswmm but always get an error. In my hydro conda environment (with python 3.11 installed but I also tried with 3.8) I do the following:

```
/opt/homebrew/Caskroom/miniforge/base/envs/hydro/bin/python -m pip install pyswmm
```

but get the error:

```
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/sh/5crwm0kd1rjc0bhslgr4mn440000gq/T/pip-install-omnumz4_/swmm-toolkit_a4bc0bd7a2fa4bc9a5a0487c398ef3f7/setup.py", line 20, in <module>
          from skbuild import setup
      ModuleNotFoundError: No module named 'skbuild'
```

So I tried to install in this same environment scikit-build (success) before running the command a second time. Now I get the error:

```
      running egg_info
      creating /private/var/folders/sh/5crwm0kd1rjc0bhslgr4mn440000gq/T/pip-pip-egg-info-ny3x3dqn/swmm_toolkit.egg-info
      writing /private/var/folders/sh/5crwm0kd1rjc0bhslgr4mn440000gq/T/pip-pip-egg-info-ny3x3dqn/swmm_toolkit.egg-info/PKG-INFO
      writing dependency_links to /private/var/folders/sh/5crwm0kd1rjc0bhslgr4mn440000gq/T/pip-pip-egg-info-ny3x3dqn/swmm_toolkit.egg-info/dependency_links.txt
      writing requirements to /private/var/folders/sh/5crwm0kd1rjc0bhslgr4mn440000gq/T/pip-pip-egg-info-ny3x3dqn/swmm_toolkit.egg-info/requires.txt
      writing top-level names to /private/var/folders/sh/5crwm0kd1rjc0bhslgr4mn440000gq/T/pip-pip-egg-info-ny3x3dqn/swmm_toolkit.egg-info/top_level.txt
      writing manifest file '/private/var/folders/sh/5crwm0kd1rjc0bhslgr4mn440000gq/T/pip-pip-egg-info-ny3x3dqn/swmm_toolkit.egg-info/SOURCES.txt'
      error: package directory 'lib' does not exist
```

Can someone help?

**Comment by bemcdonnell** [comment]
can you `pip install skbuild`?

**Comment by bemcdonnell** [comment]
I mean `scikit-build`

**Comment by aginpatrick** [comment]
Yes I did install scikit-build and now I get the error (as mentioned above): `package directory 'lib' does not exist`

**Comment by bemcdonnell** [comment]
@aginpatrick oh I just saw that you’re using Apple Silicon. @abhiramm7, do you have the step by step guide to compile SWMM-toolkit for the M1/M2?

**Comment by bemcdonnell** [comment]
We haven’t officially extended support to M1/M2 yet.

**Comment by aginpatrick** [comment]
Oh. Ok. Anyway, thank you for your help and rapid answer Bryant! Very appreciated.

**Comment by nossrednaanna** [comment]
I'm having the same problem are you planning on extending the support to M1/M2?
Thanks

**Comment by bemcdonnell** [comment]
@abhiramm7 can you provide the steps to build it for macOS?

**Comment by abhiramm7** [comment]
@aginpatrick https://github.com/pyswmm/pyswmm/wiki/Building-pyswmm-for-M1-M2-architecture has the instructions for building pyswmm for m1. I hope it helps! :)

**Comment by aginpatrick** [comment]
Great, thank you Constantine!
Patrick
