### ISSUE TITLE
setting the subcatchment.connection with pyswmm

### ISSUE THREAD

**Issue by Messi0617** [pyswmm/pyswmm#464]
Hello, I am currently using the pyswmm package and NSGA2 algorithm to optimize the subcatchment connection in a watershed. However, I found that the subcatchment.connection can only read the outlet attribute of the subcatchments in the inp file, and it cannot set the range of values for the subcatchment connection variable. I would like to know which files in pyswmm need to be modified in order to set the range of values for the subcatchment connection, similar to setting the range of values for LID area in the inp file using LidGroups(sim)['4'][0].unit_area = X[0].(vars = {'x1': Real(bounds=(0,437.8344)), 'x2': Real(bounds=(0, 408.4665)), 'x3': Real(bounds=(0, 410.6523)), 'x4': Choice(options=[207,39,206,214,121])}) I am not very familiar with the code, so I would greatly appreciate your advice and assistance. Thank you very much.

in _evaluate(self, X, out, *args, **kwargs)
27 LidGroups(sim)['5'][0].unit_area = X[1]
28 LidGroups(sim)['6'][0].unit_area = X[2]
---> 29 Subcatchments(sim)['4'].connection = X[3]
30
31 system_routing = SystemStats(sim)

AttributeError: can't set attribute

**Comment by bemcdonnell** [comment]
@Messi0617, Just so that In understand correctly.. Are you hoping to adjust the node (and/or subcatchment) that a subcatchment sends flow to before? or during the simulation?

**Comment by Messi0617** [comment]
during the simulation. Just like optimizing the LID area, optimizing the connection of catchments.

**Comment by bemcdonnell** [comment]
Addressed through PR #512 for PySWMM-v2.x
