### ISSUE TITLE
I cannot install pyswmm on an arm64 server, I use python3.9.2,pip20.3.4

### ISSUE THREAD

**Issue by t298** [pyswmm/pyswmm#467]
![picture](https://github.com/pyswmm/pyswmm/assets/49806840/dacb5ed0-6b4a-4c22-9b84-9a0147058dc6)

**Comment by karosc** [comment]
@t298, we don't publish arm64 wheels, so you'll need to build yourself.

@bemcdonnell, after some googling, I found [cibuildwheel](https://cibuildwheel.readthedocs.io/en/stable/#usage), which boasts cross-compilation support for macOS and Linux arm64. Maybe we should look into that tool to see if it is compatible with our build tool chain?

**Comment by t298** [comment]
@karosc How should I build it?

**Comment by karosc** [comment]
Are you running apple silicon? Or running linux on arm64?

**Comment by karosc** [comment]
So I got this to work on Ubuntu with arm64 architecture inside a python virtual environment. I guess our source dist doesn't quite support building from PyPI, so you'll need to clone swmm-python, build and install swmm-toolkit, then install pyswmm. 

```
git clone https://github.com/pyswmm/swmm-python.git
cd swmm-python
git submodule update -init
cd swmm-toolkit
pip install -r build-requirements.txt
python setup.py bdist_wheel
pip install dist/*.whl
pip install pyswmm
```

**Comment by t298** [comment]
I use the python version:
`root@1c4811051151:/home/swmm-python/swmm-toolkit# python3 -V
Python 3.9.2`
`root@1c4811051151:/home/swmm-python/swmm-toolkit# pip -V
pip 20.3.4 from /usr/lib/python3/dist-packages/pip (python 3.9)`
But I ran into some problems
[link](https://paste.debian.net/1290543/)

**Comment by t298** [comment]
![version](https://github.com/pyswmm/pyswmm/assets/49806840/4ec7b8f5-9a94-4ee9-97cd-1994ad5f5ad5)

**Comment by karosc** [comment]
@t298, that error looks like you didn't initialize the swmm-solver submodule. There should be CMakeLists.txt file in that directory. Did you run on the commands in my previous post?

**Comment by t298** [comment]
Is that what you're talking about? I executed it
![image](https://github.com/pyswmm/pyswmm/assets/49806840/2c28ca21-3046-40b9-a701-5f24a32f287d)

**Comment by karosc** [comment]
sorry I had a typo:  `git submodule update --init`

**Comment by t298** [comment]
Thank you. Problem solved.
![image](https://github.com/pyswmm/pyswmm/assets/49806840/f7a89b70-775f-4a4d-b95a-d36ea3cfa8c3)
