### ISSUE TITLE
How to generate hotstart file using pyswmm

### ISSUE THREAD

**Issue by gourikadam** [pyswmm/pyswmm#471]
Hello,
I wish to generate hotstart file after every single day simulation, in a continuous simulation. Can anyone guide me regarding, how to generate a hotstart file while running the simulation using pyswmm

Thank you
Regards,
Gouri

**Comment by karosc** [comment]
@gourikadam, we are in the process of releasing this feature. Stay tuned for pyswmm 2.0. Although we have not ironed our the API yet, there will b something like `sim.save_hotstart` and `sim.use_hotstart` that allow you to save hotstarts at any point in the simulation.

Thanks to @bemcdonnell  for implementing that feature in the upstream OWA SWMM.

**Comment by bemcdonnell** [comment]
@gourikadam looks like this feature is ready in a “beta” form if you’d like to try it.  @karosc just merged it into the develop branch if you want to try to install it from GitHub

**Comment by gourikadam** [comment]
Thank you @bemcdonnell . I would like to use beta version and will update once used

**Comment by karosc** [comment]
`pip install git+https://github.com/pyswmm/pyswmm.git@develop` should do it

**Comment by bemcdonnell** [comment]
@gourikadam have you had a chance to demo this?  Can you give some feedback on the experience?

**Comment by gourikadam** [comment]
Dear Team,

 

I haven’t installed the same due to machine issue at my end. Hopefully it will get resolve in this week. I will surely give feedback regarding the same.

 

Regards,

Thank you

Gouri Kadam

**Comment by gourikadam** [comment]
Dear Team,

 

Thank you for sharing the command and I am able to install the same. Can you please help me with below two queries

1.       How to find the pyswmm version which is installed using the below mentioned command?

2.       Where to find the help/tutorial for generating the hotstart file using pyswmm?

 

Thank you

 

Gouri

**Comment by karosc** [comment]
@gourikadam

1. The version of pyswmm you installed is the [develop branch](https://github.com/pyswmm/pyswmm/tree/develop)
2. There is no tutorial, you'll just use the functions I linked before in [the simulation class](https://github.com/pyswmm/pyswmm/blob/develop/pyswmm/simulation.py#L666-L686). You can also look in [the unit tests for a usage example](https://github.com/pyswmm/pyswmm/blob/develop/pyswmm/tests/test_simulation.py#L145-L172)
