### ISSUE TITLE
... Run Completeswig/python detected a memory leak of type 'struct Handle *', no destructor found.

### ISSUE THREAD

**Issue by t298** [pyswmm/pyswmm#482]
![image](https://github.com/pyswmm/pyswmm/assets/49806840/8622225c-3bc3-4dd4-b16d-641a681ba9bb)
Using python3.11.1 will cause this problem, even if it works out, but I will be using pyswmm on the server side of grpc, so this problem will cause my second calculation to fail

**Comment by bemcdonnell** [comment]
@t298 Are you calling a specific function or just running a model?  I think it needs to be investigated.  Depending on where, it might need to be elevated to the USEPA/SWMM repo.

**Comment by JohnEngineer** [comment]
I had this issue, and it was very simple to fix. I don't think this is a bug within pyswmm. The error occurred because I had used the "out = Output(output_file)" statement twice in the same section of code. Deleting the redundant "out =" statement eliminated the memory leak.

**Comment by bemcdonnell** [comment]
@JohnEngineer, thanks for reporting this. Just so I understand better (and so I can update the documentation), can you put a code snippet with the related lines to your “out” instances in the case where you had multiple open? Also, how were you managing closing those?  We typically recommend using the “with” context manager to open the output files since this automatically cleans up after itself.

**Comment by JohnEngineer** [comment]
Good morning, Bryant:

Here’s the snippet. The “out = Output(output_file)” statement had been executed previously in the code. I am not closing out—which may be leading to some other problems. Thanks for your help!

    out = Output(output_file)

    flutter_scores = {}
    flow_difference_list = []  # List to store hydrographs with more than 1 flow rate difference (for later use in checking initial conditions)

    for i, link in enumerate(LinkNames):
        data_to_plot = out.link_series(link, LinkAttribute.FLOW_RATE)
        y = [data_to_plot[key] for key in data_to_plot.keys()]

        # Check for flow rate difference of more than 1 in the first two timesteps
        flow_difference = abs(y[1] - y[0])
        if flow_difference > 1:
            flow_difference_list.append([link, flow_difference])

        flutter_score = calculate_weighted_flutter(y)

        if flutter_score > 0:
            flutter_scores[link] = flutter_score



John N. Paine, PE, PH, CFM
GKY & Associates, Inc.

**Comment by JohnEngineer** [comment]
Thanks, again, Bryant. I refactored as follows (using the 'with' context manager), and that seems to have solved my problem.

    # Remember, the out file was opened previously in the code and is still open [i.e., we don't need another out = Output(output_file) statement]
    # out = Output(output_file)

    flutter_scores = {}
    flow_difference_list = []  # List to store hydrographs with more than 1 flow rate difference (for later use in checking initial conditions)

    with Output(output_file) as new_out:
        for i, link in enumerate(LinkNames):
            data_to_plot = new_out.link_series(link, LinkAttribute.FLOW_RATE)
            y = [data_to_plot[key] for key in data_to_plot.keys()]

            # Check for flow rate difference of more than 1 in the first two timesteps
            flow_difference = abs(y[1] - y[0])
            if flow_difference > 1:
                flow_difference_list.append([link, flow_difference])

            flutter_score = calculate_weighted_flutter(y)
            
            if flutter_score > 0:
                flutter_scores[link] = flutter_score
